backend/src/Entity/Release.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ReleaseRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Attribute\Groups;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReleaseRepository::class)]
#[ORM\Table(name: '`release`')]
#[UniqueEntity('slug')]
#[Vich\Uploadable]
class Release
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['api.release.list'])]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    #[Assert\Length(min: 1, groups: ['Extra'])]
    #[Assert\Length(max: 150, groups: ['Extra'])]
    #[Groups(['api.release.list'])]
    private ?string $title = null;

    #[ORM\Column(length: 150)]
    #[Assert\Length(min: 1)]
    #[Assert\Length(max: 150)]
    #[Assert\Regex('/^[a-z0-9]+(?:-[a-z0-9]+)*$/', message: "This is not a valid slug.")]
    #[Groups(['api.release.list'])]
    private ?string $slug = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    #[Assert\Positive()]
    #[Assert\GreaterThan(value: 1000)]
    #[Groups(['api.release.list'])]
    private ?int $release_date = null;

    #[Vich\UploadableField(mapping: 'cover_images', fileNameProperty: 'cover')]
    private ?File $coverFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['api.release.list'])]
    private ?string $cover = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Groups(['api.release.list'])]
    private ?string $barcode = null;

    /**
     * @var Collection<int, Artist>
     */
    #[ORM\ManyToMany(targetEntity: Artist::class, inversedBy: 'releases')]
    #[Groups(['api.release.list'])]
    private Collection $artists;

    #[ORM\Column]
    #[Groups(['api.release.list'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    #[Groups(['api.release.list'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'releases')]
    #[Groups(['api.release.list'])]
    private ?Shelf $shelf = null;

    #[ORM\ManyToOne(inversedBy: 'releases')]
    #[Groups(['api.release.list'])]
    private ?Format $format = null;

    /**
     * @var Collection<int, Genre>
     */
    #[ORM\ManyToMany(targetEntity: Genre::class, mappedBy: 'releases')]
    #[Groups(['api.release.list'])]
    private Collection $genres;

    #[ORM\Column(type: 'boolean', options: ['default' => false])]
    #[Groups(['api.release.list'])]
    private bool $featured = false;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'releases')]
    private Collection $users;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Groups(['api.release.list'])]
    private ?string $note = null;

    public function __construct()
    {
        $this->artists = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseDate(): ?int
    {
        return $this->release_date;
    }

    public function setReleaseDate(?int $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $coverFile
     */
    public function setCoverFile(?File $coverFile = null): void
    {
        $this->coverFile = $coverFile;

        if (null !== $coverFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getCoverFile(): ?File
    {
        return $this->coverFile;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(?string $cover): static
    {
        $this->cover = $cover;

        return $this;
    }

    public function getBarcode(): ?string
    {
        return $this->barcode;
    }

    public function setBarcode(?string $barcode): static
    {
        $this->barcode = $barcode;

        return $this;
    }

    /**
     * @return Collection<int, Artist>
     */
    public function getArtists(): Collection
    {
        return $this->artists;
    }

    public function addArtist(Artist $artists): static
    {
        if (!$this->artists->contains($artists)) {
            $this->artists->add($artists);
        }

        return $this;
    }

    public function removeArtist(Artist $artist): static
    {
        $this->artists->removeElement($artist);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getShelf(): ?Shelf
    {
        return $this->shelf;
    }

    public function setShelf(?Shelf $shelf): static
    {
        $this->shelf = $shelf;

        return $this;
    }

    public function getFormat(): ?Format
    {
        return $this->format;
    }

    public function setFormat(?Format $format): static
    {
        $this->format = $format;

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): static
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
            $genre->addRelease($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): static
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeRelease($this);
        }

        return $this;
    }

    public function isFeatured(): bool
    {
        return $this->featured;
    }

    public function setFeatured(bool $featured): static
    {
        $this->featured = $featured;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        $this->users->removeElement($user);

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): static
    {
        $this->note = $note;

        return $this;
    }
}

backend/src/Controller/ReleaseController.php
<?php

namespace App\Controller;

use App\Form\ScanType;
use App\Entity\Release;
use App\Form\SearchType;
use App\Form\ReleaseType;
use Psr\Log\LoggerInterface;
use App\Service\DiscogsService;
use App\Service\ReleaseService;
use App\Service\MusicBrainzService;
use App\Repository\ReleaseRepository;
use App\Service\CoverArtArchiveService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

#[Route('/release', name: 'release.')]
#[IsGranted('ROLE_ADMIN', message: 'You need admin privileges to view this page.')]
final class ReleaseController extends AbstractController
{
    private $coverDir;

    public function __construct(
        private ParameterBagInterface $params,
        private LoggerInterface $logger,
        private HttpClientInterface $client,
        private SluggerInterface $slugger
    ) {
        $this->coverDir = $params->get('images_dir') . '/covers';
    }

    #[Route('/', name: 'index', methods: ['GET', 'POST'])]
    public function index(ReleaseRepository $releaseRepository, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);
        $limit = 10;

        $form = $this->createForm(SearchType::class);
        $form->handleRequest($request);

        $searchTerm = '';
        if ($form->isSubmitted() && $form->isValid()) {
            $searchTerm = $form->get('terms')->getData();
        }

        $releases = $releaseRepository->paginatedReleases($page, $limit, $searchTerm);
        $maxpage = ceil($releases->count() / $limit);

        return $this->render('release/index.html.twig', [
            'releases' => $releases,
            'maxPage' => $maxpage,
            'page' => $page,
            'coverDir' => $this->coverDir,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/scan', name: 'scan', methods: ['GET', 'POST'])]
    public function scan(
        Request $request,
        DiscogsService $discogsService,
    ): Response {
        $barcodeValue = [];
        $releases = null;

        $form = $this->createForm(ScanType::class, null);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $barcodeValue = $form->get('barcode')->getData();

            try {
                $releases = $discogsService->getReleaseByBarcode($barcodeValue);
            } catch (\Exception $e) {
                return $this->json([
                    'error' => $e->getMessage()
                ], 500);
            }

            // Store the data in the session
            $session = $request->getSession();
            $session->set('barcode', $barcodeValue);
            $session->set('releases', $releases);

            // Redirect to the same route
            return $this->redirectToRoute('release.scan');
        }

        // Get any data from the session
        $session = $request->getSession();
        $barcodeValue = $session->get('barcode', '');
        $releases = $session->get('releases', null);

        // Clear the session data after retrieving it
        if ($request->getMethod() === 'GET' && !$form->isSubmitted()) {
            $session->remove('barcode');
            $session->remove('releases');
        }

        return $this->render('release/scan.html.twig', [
            'form' => $form,
            'barcode' => $barcodeValue,
            'releases' => $releases
        ]);
    }

    #[Route('/scan/add', name: 'scan.add', methods: ['POST'])]
    public function scanAdd(
        Request $request,
        ReleaseService $releaseService
    ): Response {
        // Get the release ID and barcode from the form submission
        $releaseId = $request->request->get('release_id');
        $barcode = $request->request->get('barcode');

        if (!$releaseId) {
            $this->addFlash('error', 'No release ID provided.');
            return $this->redirectToRoute('scan');
        }

        if (!$barcode) {
            $this->addFlash('error', 'No barcode provided.');
            return $this->redirectToRoute('scan');
        }

        try {
            $release = $releaseService->addRelease($releaseId, $barcode);
        } catch (\Exception $e) {
            $this->addFlash('danger', $e->getMessage());
            return $this->redirectToRoute('release.scan');
        }

        $this->addFlash('success', 'Release "' . $release->getTitle() . '" added successfully.');
        return $this->redirectToRoute('release.scan');
    }

    #[Route('/{barcode}/fetch-cover', name: 'fetch-cover', methods: ['GET', 'POST'], requirements: ['barcode' => '\d+'])]
    public function fetchCover(
        string $barcode,
        Request $request,
        MusicBrainzService $musicBrainzService,
        CoverArtArchiveService $coverService
    ) {
        try {
            $releaseData = $musicBrainzService->getReleaseByBarcode($barcode);
            $releases = $releaseData["releases"];
        } catch (\Exception $e) {
            return $this->json([
                'error' => $e->getMessage()
            ], 500);
        }

        // Attach cover art
        foreach ($releases as $key => $release) {
            $coverUrl = $coverService->getCoverArtByMbid($release['id']);
            $release['cover'] = $coverUrl;
            $releases[$key] = $release;
        }

        return $this->render('release/fetch-cover.html.twig', [
            'releases' => $releases,
            'barcode' => $barcode,
            'page' => $request->query->get('page', 1)
        ]);
    }

    #[Route('/update-cover', name: 'update.cover', methods: ['POST'])]
    public function updateCover(
        Request $request,
        EntityManagerInterface $em,
        ReleaseRepository $releaseRepository,
        MusicBrainzService $musicBrainzService,
        ReleaseService $releaseService
    ): Response {
        // Get the values from the form submission
        $page = $request->request->get('page');
        $releaseId = $request->request->get('release_id');
        $barcode = (string) $request->request->get('barcode', '', \FILTER_DEFAULT);

        if (!$releaseId) {
            $this->addFlash('error', 'No release ID provided');
            return $this->redirectToRoute('release.index', ['page' => $page]);
        }

        // Fetch the complete release data
        try {
            $releaseData = $musicBrainzService->getReleaseWithCoverArt($releaseId);
        } catch (\Exception $e) {
            return $this->json([
                'error' => $e->getMessage()
            ], 500);
        }

        // Get the release
        $release = $releaseRepository->findOneBy(['barcode' => $barcode]);

        if (!$release) {
            $this->addFlash('warning', 'Release with barcode "' . $barcode . '" does not exist in the database.');
            return $this->redirectToRoute('release.index', ['page' => $page]);
        }

        if ($releaseData['cover']) {
            $coverPath = $releaseService->downloadCovertArt($releaseData['cover'], $releaseId);
            $release->setCover($coverPath);
        }

        $em->flush();

        $this->addFlash('success', 'Cover art successfully added for release "' . $release->getTitle() . '".');
        return $this->redirectToRoute('release.index', ['page' => $page]);
    }

    #[Route('/create', name: 'create', methods: ['GET', 'POST'])]
    public function create(Request $request, EntityManagerInterface $em)
    {
        $release = new Release();
        $form = $this->createForm(ReleaseType::class, $release);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($release);
            $em->flush();
            $this->addFlash('success', 'The release has been successfully added.');
            return $this->redirectToRoute('release.index');
        }

        return $this->render('release/create.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'], requirements: ['id' => Requirement::DIGITS])]
    public function edit(Release $release, Request $request, EntityManagerInterface $em)
    {
        $form = $this->createForm(ReleaseType::class, $release);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            $this->addFlash('success', 'The release has been successfully updated.');
            return $this->redirectToRoute('release.index');
        }

        return $this->render('release/edit.html.twig', [
            'release' => $release,
            'form' => $form
        ]);
    }

    #[Route('/{id}/confirm-delete', name: 'delete', methods: ['GET', 'POST'])]
    public function confirmDelete(Release $release, Request $request, ReleaseService $releaseService): Response
    {
        $form = $this->createFormBuilder()
            ->add('delete', SubmitType::class, [
                'label' => 'Delete',
            ])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $releaseService->deleteRelease($release);
                $this->addFlash('success', 'The release has been successfully deleted.');
            } catch (\Exception $e) {
                $this->addFlash('error', 'An error occurred while deleting the release. Please try again.');

backend/templates/release/confirm_delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Delete release:
  {{ release.title }}
{% endblock %}

{% block body %}
  <div class="max-w-screen-xl mx-auto">
    <h1 class="title mb-4">
      Confirm Deletion
    </h1>

    <p>
      Are you sure you want to delete the release "
      {{ release.title }}
      "?
    </p>

    {{ form_start(form) }}
    <div class="flex my-4 space-x-3">
      {{ form_widget(form.delete, {'attr': {'class': 'btn-danger', type: 'submit', name: 'delete', id: 'delete' }}
      ) }}
      <a href="{{ path('release.index') }}" class="btn-primary-outlined">
        Cancel
      </a>
    </div>
    {{ form_end(form) }}

  </div>
{% endblock %}

backend/templates/release/fetch-cover.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Fetch a release cover art
{% endblock %}

{% block body %}
	<div class="max-w-screen-xl mx-auto">

		<h1 class="font-bold text-3xl text-slate-500 mb-4">
			Fetch a release cover art
		</h1>

		{% if releases is not null %}
			<div class="mx-auto mt-4"></div>
			<h2 class="font-bold text-2xl text-slate-500 mb-4">
				Results for barcode:
				{{ barcode }}
			</h2>

			{% if releases|length > 0 %}
				<div class="releases-container">
					{% for release in releases %}
						{% if release.cover is defined %}
							{% if release.cover != '' %}
								<img src="{{ release.cover }}" alt="{{ release.title }}" class="float-right" style="width: 150px"/>
							{% endif %}
						{% endif %}
						<form action="{{ path('release.update.cover') }}" method="post">
							<div class="release-item mb-2 rounded bg-gray-900 p-4">
								<h3 class="font-bold text-xl text-slate-500 mb-4 flex items-center">
									<button type="submit" class="text-orange-500 hover:text-orange-800 mr-2" aria-label="Add" title="Add">
										<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
											<path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
										</svg>
									</button>
									{{ release.title }}
								</h3>
								{% if release['artist-credit'] is defined %}
									<p>
										Artist:
										{% for art in release['artist-credit'] %}
											{{ art.name }}
											{% if not loop.last %}
												,
											{% endif %}
										{% endfor %}
									</p>
								{% endif %}

								<div class="grid justify-items-start">
									{% if release.date is defined %}
										<p>
											Date:
											{{ release.date }}
										</p>
									{% endif %}

									{% if release.media is defined %}
										<p class="clear-both">
											Media:
											{% for media in release.media %}
												{{ media.format }}
												{% if not loop.last %}
													,
												{% endif %}
											{% endfor %}
											{% if release.packaging is defined %}
												- Packaging:
												{{ release.packaging }}
											{% endif %}
										</p>
									{% endif %}
								</div>

								<input type="hidden" name="page" value="{{ page }}">
								<input type="hidden" name="release_id" value="{{ release.id }}">
								<input type="hidden" type="text" name="barcode" value="{{ barcode }}">
							</div>
						</form>
					{% endfor %}
				</div>
			{% else %}
				<p>
					No releases found for this barcode.
				</p>
			{% endif %}
		{% endif %}

		<p class="mt-4">
			<a href="{{ path('release.index', {page: page}) }}" class="btn-primary">Back</a>
		</p>

	</div>
{% endblock %}

backend/templates/release/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Releases
{% endblock %}

{% block body %}
    <div class="max-w-screen-xl mx-auto">

        <div class="flex justify-between items-center">
            <h1 class="title mb-4">
                Releases (
                {{ releases.getTotalItemCount() }}
                )
            </h1>
        </div>

        <div class="flex justify-between items-start mb-4">
            <div>
                {{ form_start(form, {'attr': {'class': 'mx-auto'} }) }}
                {{ form_widget(form.terms, {'attr': {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 'placeholder': 'Search'} }) }}
                {{ form_widget(form.search, {'attr': {'class': 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800', type: 'submit', name: 'search', id: 'search'} }) }}
                <a href="{{ path('release.index') }}" class="text-white bg-gray-500 hover:bg-gray-600 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
                    Reset
                </a>
                {{ form_end(form) }}
            </div>
            <a href="{{ path('release.create') }}" class="text-zinc-500 hover:text-zinc-400 mr-8">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                </svg>
            </a>
        </div>

        <div class="relative overflow-x-auto mt-4">
            <table class="table-table">
                <thead class="table-thead">
                    <tr>
                        <th class="px-6 py-4">
                            Cover art
                        </th>
                        <th scope="col" class="px-6 py-3">
                            {{ knp_pagination_sortable(releases, 'Title', 'r.title') }}
                        </th>
                        <th class="px-6 py-4">
                            Artist
                        </th>
                        <th class="px-6 py-4">
                            Format
                        </th>
                        <th class="px-6 py-4">
                            Year
                        </th>
                        <th class="px-6 py-4">
                            Barcode
                        </th>
                        <th class="px-6 py-4 text-right"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for release in releases %}
                        <tr class="table-tr">
                            <td class="px-6 py-4 w-[100px]">
                                {% if release.cover|length > 0 %}
                                    <img src="/{{ coverDir ~ release.cover }}" alt="{{ release.title }}" style="width: 100px"/>
                                {% else %}
                                    <div class="w-[100px] h-[100px] bg-gray-200 flex items-center justify-center text-center text-sm font-medium text-gray-600 border border-gray-300">
                                        No cover
                                    </div>
                                {% endif %}
                            </td>
                            <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{ release.title }}
                                {% if release.shelf %}
                                    <br/>
                                    <span class="text-xs text-gray-500">
                                        Shelf:
                                        {{ release.shelf.location }}
                                    </span>
                                {% endif %}
                            </td>
                            <td class="px-6 py-4">
                                {% if release.artists|length > 0 %}
                                    {{ release.artists|map(artist => artist.name)|join(', ') }}
                                {% else %}
                                    <em class="text-xs text-gray-500">
                                        No artists
                                    </em>
                                {% endif %}
                            </td>
                            <td class="px-6 py-4">
                                {% if release.format is not null %}
                                    {{ release.format.name }}
                                {% else %}
                                    <em class="text-xs text-gray-500">
                                        Missing
                                    </em>
                                {% endif %}
                            </td>
                            <td class="px-6 py-4">
                                {{ release.releaseDate }}
                            </td>
                            <td class="px-6 py-4">
                                {{ release.barcode }}
                            </td>
                            <td class="px-6 py-4 text-right">
                                <div class="flex space-x-3 justify-end">
                                    {% if release.cover|length == 0 and release.barcode %}
                                        <a href="{{ path('release.fetch-cover', {barcode: release.barcode, page: page}) }}" class="text-zinc-500 hover:text-zinc-400 mr-4" title="Fetch cover">
                                            <!-- parse-ignore-start -->
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z"/>
                      </svg>
                      <!-- parse-ignore-end -->
                                        </a>
                                    {% endif %}
                                    <a href="{{ path('release.edit', {id: release.id}) }}" title="Edit" class="text-zinc-500 hover:text-zinc-400 mr-4">
                                        <!-- parse-ignore-start -->
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10"/>
                    </svg>
                    <!-- parse-ignore-end -->
                                    </a>
                                    <form action="{{ path('release.delete', {id: release.id}) }}" method="get">
                                        <button type="submit" title="Delete" class="text-zinc-500 hover:text-red-700 cursor-pointer">
                                            <!-- parse-ignore-start -->
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                      </svg>
                      <!-- parse-ignore-end -->
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="my-4">
                {{ knp_pagination_render(releases, 'partials/tailwind_pagination.html.twig') }}
            </div>
        </div>

    </div>
{% endblock %}